CREATE OR REPLACE FUNCTION public.sp_aposta_jogo_apostado_inserir (
  "P_DATA_JOGO" varchar,
  "P_HORA_JOGO" varchar,
  "P_JOGO_APOSTADO" integer,
  "P_TIPO_APOSTA" varchar,
  "P_VAL_APOSTA" double precision
)
RETURNS varchar AS
$body$
DECLARE
 P_MSG_RETORNO VARCHAR = '';
 P_SEQUENCIAL integer = 0;
 BEGIN 
 P_SEQUENCIAL = currval('aposta_seq_aposta_seq'); 
 INSERT INTO jogos_apostado (COD_APOSTA, DATA_JOGO, HORA_JOGO, COD_JOGO, TIPO_APOSTA, VAL_TAXA)
  VALUES (P_SEQUENCIAL, $1, $2, $3, $4, $5);

 
 P_MSG_RETORNO = 'OK';
 RETURN P_MSG_RETORNO;
 EXCEPTION 
 WHEN UNIQUE_VIOLATION THEN
 P_MSG_RETORNO = SQLERRM;
 RETURN P_MSG_RETORNO;
 WHEN INTEGRITY_CONSTRAINT_VIOLATION THEN 
 P_MSG_RETORNO = SQLERRM;
 RETURN P_MSG_RETORNO; 
 END;
$body$
LANGUAGE 'plpgsql'
VOLATILE
CALLED ON NULL INPUT
SECURITY INVOKER
COST 100;