CREATE OR REPLACE FUNCTION public.sp_aposta_inserir (
  "P_COD_CAMBISTA" integer,
  "P_NOME_APOSTADOR" varchar,
  "P_VAL_APOSTA" double precision,
  "P_VAL_COMISSSAO" double precision,
  "P_VAL_RETORNO_POSSIVEL" double precision
)
RETURNS varchar AS
$body$
DECLARE
 P_MSG_RETORNO VARCHAR = '';   
 P_SEQUENCIAL INTEGER = 0;
 BEGIN 



 
 INSERT INTO APOSTA (COD_CAMBISTA, NOME_APOSTADOR, VAL_APOSTADO, VAL_COMISSAO, VAL_RETORNO_POSSIVEL)
  VALUES ($1, $2, $3, $4, $5);
 
 P_SEQUENCIAL = currval('aposta_seq_aposta_seq'); 
 P_MSG_RETORNO = 'OK';
 
 RETURN P_MSG_RETORNO;
 EXCEPTION 
 WHEN UNIQUE_VIOLATION THEN
 P_MSG_RETORNO = SQLERRM;
 RETURN P_MSG_RETORNO;
 WHEN INTEGRITY_CONSTRAINT_VIOLATION THEN 
 P_MSG_RETORNO = SQLERRM;
 RETURN P_MSG_RETORNO; 
 END;
$body$
LANGUAGE 'plpgsql'
VOLATILE
CALLED ON NULL INPUT
SECURITY INVOKER
COST 100;