CREATE OR REPLACE FUNCTION public.sp_cambista_autenticar (
  out "P_CS_GERAL" refcursor,
  "P_APELIDO" varchar,
  "P_SENHA" varchar
)
RETURNS refcursor AS
$body$
DECLARE
 P_CS_GERAL REFCURSOR;

BEGIN

OPEN $1 FOR 
  SELECT C.*, CC.* FROM cambista C, CONFIGURACAO_CAMBISTA CC WHERE C.APELIDO_CAMBISTA = $2 AND C.SENHA_CAMBISTA = $3
  AND CC.COD_CAMBISTA = C.SEQ_CAMBISTA;
 END;
$body$
LANGUAGE 'plpgsql'
VOLATILE
CALLED ON NULL INPUT
SECURITY INVOKER
COST 100;