CREATE OR REPLACE FUNCTION sp_campeonato_remover("P_SEQ_CAMPEONATO" integer)
  RETURNS character varying AS
$BODY$
DECLARE
 P_MSG_RETORNO VARCHAR = '';
 BEGIN 
 
 DELETE FROM campeonato WHERE seq_campeonato = $1;

 P_MSG_RETORNO = 'OK';
 RETURN P_MSG_RETORNO;
 EXCEPTION 
 WHEN UNIQUE_VIOLATION THEN
 P_MSG_RETORNO = SQLERRM;
 RETURN P_MSG_RETORNO;
 WHEN INTEGRITY_CONSTRAINT_VIOLATION THEN 
 P_MSG_RETORNO = SQLERRM;
 RETURN P_MSG_RETORNO; 
 END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;